kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:45a1ad5919f0b6acf0f0cf730e9434abfae11fe6
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:e7a92d9f3282039eac5fb1b07cac2b8664cbf0ad
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db
services:
  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
