kernel:
  image: linuxkit/kernel:4.9.34
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:7e3d51e6ab5896ecb36a4829450f7430f2878927
  - linuxkit/runc:9f7aad4eb5e4360cc9ed8778a5c501cce6e21601
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:bdc99eeedc224439ff237990ee06e5b992c8c1ae
services:
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:4f85d8de3f6f45973a8c88dc8fba9ec596e5495a
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
