kernel:
  image: linuxkit/kernel:5.10.92
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:7e3d51e6ab5896ecb36a4829450f7430f2878927
  - linuxkit/runc:9f7aad4eb5e4360cc9ed8778a5c501cce6e21601
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.5
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.9
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - KAPACITOR_URL=http://127.0.0.1:9092
