# Simple example of using an external logging service
kernel:
  image: linuxkit/kernel:5.10.92
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:7e3d51e6ab5896ecb36a4829450f7430f2878927
  - linuxkit/runc:9f7aad4eb5e4360cc9ed8778a5c501cce6e21601
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
  - linuxkit/memlogd:014f86dce2ea4bb2ec13e92ae5c1e854bcefec40
onboot:
  - name: sysctl
    image: linuxkit/sysctl:bdc99eeedc224439ff237990ee06e5b992c8c1ae
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
# Inside the getty type `/proc/1/root/usr/bin/logread -F` to follow the log
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    env:
     - INSECURE=true
# A service which generates log messages for testing
  - name: write-to-the-logs
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while /bin/true; do echo hello $(date); sleep 1; done" ]
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:4d8aa07d4a7130239fc62b09f33e3401ecf62a38
  - name: kmsg
    image: linuxkit/kmsg:b2f6cd4ce9041120e30a4b5ab36bb8db4f5eb458
