kernel:
  image: linuxkit/kernel:5.10.92
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:7e3d51e6ab5896ecb36a4829450f7430f2878927
  - linuxkit/runc:9f7aad4eb5e4360cc9ed8778a5c501cce6e21601
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:bdc99eeedc224439ff237990ee06e5b992c8c1ae
  - name: sysfs
    image: linuxkit/sysfs:c3bdb00c5e23bf566d294bafd5f7890ca319056f
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:7efa07559dd23cb4dbebfd3ab48c50fd33625918
  - name: mount
    image: linuxkit/mount:422b219bb1c7051096126ac83e6dcc8b2f3f1176
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:4f85d8de3f6f45973a8c88dc8fba9ec596e5495a
  - name: ntpd
    image: linuxkit/openntpd:d6c36ac367ed26a6eeffd8db78334d9f8041b038
  - name: docker
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/run:/var/run
     - /etc/html:/var/html
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: compose
    image: linuxkitprojects/compose:111f9f32a933c9e7acbf3ccfc13fedbdfce8224f
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: var/lib/docker
    directory: true
  - path: etc/html/a/index.html
    source: html-a.html
  - path: etc/html/b/index.html
    source: html-b.html
  - path: etc/compose/docker-compose.yml
    source: docker-compose.yml
  - path: etc/compose/images/nginx:alpine.tar
    source: image-cache/nginx:alpine.tar
  - path: etc/compose/images/traefik.tar
    source: image-cache/traefik.tar
trust:
  org:
    - linuxkit
    - library
